name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
      - run: pnpm install
      - run: pnpm dev:prepare
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
      - uses: codecov/codecov-action@v2
      - name: Release Edge
        if: |
          github.event_name == 'push' &&
          !contains(github.event.head_commit.message, '[skip-release]') &&
          !startsWith(github.event.head_commit.message, 'chore') &&
          !startsWith(github.event.head_commit.message, 'docs') &&
          !startsWith(github.event.head_commit.message, 'test')
        run: ./scripts/release-edge.sh
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}